[project]
name = "rosbags-reading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.7",
    "rosbags>=0.11.0",
    "numpy>=2.2.6",
    "onnxruntime>=1.23.2",
]
